name: CI
on: [push, pull_request]
jobs:
  cs-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: castor-php/setup-castor@v0.1.0
      - name: 'php-cs-fixer check'
        run: 'castor qa:cs:check'
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/
          key: composer-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: 8.3
          coverage: none
      - name: composer install
        run: composer update --prefer-stable
      - name: setup
        uses: castor-php/setup-castor@v0.1.0
      - name: 'phpstan check'
        run: 'castor qa:phpstan'
  tests:
    runs-on: ubuntu-latest
    name: tests
    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - 8.2
          - 8.3
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/
          key: composer-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: '${{ matrix.php-versions }}'
          coverage: none
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-stable
      - name: tests
        run: vendor/bin/phpunit
  tests-lowest:
    runs-on: ubuntu-latest
    name: tests-lowest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/
          key: composer-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: 8.2
          coverage: none
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-stable --prefer-lowest
      - name: tests
        run: vendor/bin/phpunit
